In [2]:
import sys
import seaborn as sb
import pandas as pd
import numpy as np
from enum import Enum
from pathlib import Path
import matplotlib.pyplot as plt

In [3]:
current_dir = Path.cwd()
project_root = current_dir.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))
    print("Done")

Done


In [4]:
class Distributions(Enum):
    NORMAL = "normal"
    UNIFORM = "uniform"
    EXPONENTIAL = "exponential"
    CAUCHY = "cauchy"

In [5]:
K = int(input("Enter the no of distributions to fit: "))
dist_to_use = []
for i in range(K):
    dist_to_use.append(input(f"{i+1}th distribution to use: "))

In [6]:
dist_to_use

['normal', 'normal', 'cauchy', 'exponential']

In [16]:
def multivariate_normal(X: np.array, mean: np.array, cov: np.array) -> np.array:
    diff = X - mean
    num = np.exp(-0.5*(np.sum((diff @ np.linalg.inv(cov)) * diff, axis=1)))
    deno = np.sqrt((2*np.pi)**len(mean) * np.linalg.det(cov))
    return num/deno

In [17]:
no_of_features = 5
mean = np.random.randint(low=0, high=10, size=5).reshape(1, -1)
cov = np.eye(no_of_features)

In [18]:
no_of_rows = 10
X = np.random.uniform(size=(no_of_rows, no_of_features))

In [19]:
mean.shape, X.shape

((1, 5), (10, 5))

In [20]:
probs = multivariate_normal(X=X, mean=mean, cov=cov)

In [21]:
probs

array([1.82137419e-25, 2.69478188e-25, 1.59658642e-25, 3.73820074e-24,
       1.67057335e-26, 5.11181905e-25, 3.04720789e-24, 2.70241326e-27,
       4.18155775e-25, 1.49829720e-25])

### Exponential Distribution

In [25]:
x = np.array([[1,3,1,-1,5],
              [1,5,8,2,-2],
              [4,7,8,2,1]])

mask = x>0
np.where(mask, x, 0)

array([[1, 3, 1, 0, 5],
       [1, 5, 8, 2, 0],
       [4, 7, 8, 2, 1]])

In [ ]:
def exponential_pdf(x, scale):
    scale = max(scale, 1e-15)  
    pdf_values = np.zeros_like(x, dtype=float)
    mask = x > 0
    pdf_values[mask] = (1.0 / scale) * np.exp(-x[mask] / scale)
    return pdf_values + 1e-15

In [102]:
def exponential_log_pdf(x, scale):
    scale = max(scale, 1e-15)
    log_pdf = -np.log(scale) - (x / scale)
    log_pdf[x <= 0] = -np.inf
    return log_pdf

In [103]:
def multivariate_exponential_log(X: np.array, scale_vec: np.array) -> np.array:
    log_probs = np.zeros((X.shape[0], 1))
    
    for i in range(X.shape[1]):
        col_log_pdf = exponential_log_pdf(X[:, i], scale_vec[i].item())
        log_probs += col_log_pdf.reshape(-1, 1)
        
    return log_probs

In [104]:
no_of_features = 5
scales = np.random.randint(low=1, high=10, size=no_of_features).reshape((1, no_of_features))
X = np.random.uniform(size=(10, no_of_features))

In [105]:
X.shape, scales.shape

((10, 5), (1, 5))

In [107]:
multivariate_exponential_log(X=X, scale_vec=scales.flatten())

array([[-8.48083707],
       [-9.16410639],
       [-9.05406705],
       [-8.37944908],
       [-8.3944196 ],
       [-8.35174858],
       [-8.60912236],
       [-8.89830724],
       [-8.07979375],
       [-8.64741518]])